# Generated by Django 4.2.16 on 2024-10-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestuff', '0004_alter_community_options_event_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
