# Generated by Django 4.2.16 on 2024-10-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestuff', '0006_defaultavatar_alter_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
