# Generated by Django 4.2.16 on 2024-10-19 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codestuff', '0008_alter_landingimage_options_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internprofile',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codestuff.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
