# Generated by Django 4.2.16 on 2024-10-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestuff', '0009_alter_internprofile_profile_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Profile picture'),
        ),
    ]
