# Generated by Django 4.2.16 on 2024-10-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestuff', '0002_landingimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='keywords',
        ),
        migrations.AddField(
            model_name='profile',
            name='keywords',
            field=models.ManyToManyField(to='codestuff.keywords'),
        ),
    ]
