# Generated by Django 4.2.16 on 2024-10-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestuff', '0010_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alternate',
            field=models.TextField(blank=True, null=True, verbose_name='Alternate text'),
        ),
    ]
