# Generated by Django 4.2.16 on 2024-10-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestuff', '0011_alter_profile_alternate'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='ability_to_create_rooms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='ability_to_delete_rooms',
            field=models.BooleanField(default=False),
        ),
    ]
