# Generated by Django 4.2.16 on 2024-10-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestuff', '0012_role_ability_to_create_rooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityroleassignment',
            name='ability_to_add_people',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='communityroleassignment',
            name='ability_to_add_rooms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communityroleassignment',
            name='ability_to_assign_roles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communityroleassignment',
            name='ability_to_ban_people',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communityroleassignment',
            name='ability_to_create_rooms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communityroleassignment',
            name='ability_to_delete_rooms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communityroleassignment',
            name='ability_to_kick_people',
            field=models.BooleanField(default=False),
        ),
    ]
