# Generated by Django 4.2.16 on 2024-10-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestuff', '0014_alter_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
