# Generated by Django 4.2.16 on 2024-10-20 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codestuff', '0016_alter_friend_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalprofile',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codestuff.major'),
        ),
        migrations.AlterField(
            model_name='internprofile',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codestuff.major'),
        ),
    ]
