# Generated by Django 4.2.16 on 2024-10-20 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codestuff', '0017_personalprofile_major_alter_internprofile_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='personal_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
