# Generated by Django 4.2.16 on 2024-10-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestuff', '0020_personalprofile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internprofile',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
